name: resuable workflow user

on:
  workflow_dispatch:
jobs:
  do-it:
   runs-on: unbuntu-latest
   
     
  docker:
      uses: Akankshaanshu/node-hello/.github/workflows/action.yml@master
      with:
       image_name: myimage
      secrets:
       DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
       DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    
 
